export const singleNumberContact = {
  recordID: '177C371E-701D-42F8-A03B-C61CA31627F6',
  backTitle: '',
  jobTitle: 'Producer',
  emailAddresses: [],
  urlAddresses: [],
  phoneNumbers: [{label: 'mobile', number: '(555) 564-8583'}],
  postalAddresses: [],
  thumbnailPath: '',
  company: '',
  middleName: '',
  imAddresses: [],
  givenName: 'Kate',
  birthday: {day: 20, month: 1, year: 1978},
  hasThumbnail: false,
  familyName: 'Bell',
  isStarred: false,
  prefix: '',
  suffix: '',
  displayName: '',
  note: '',
  department: '',
};

export const multiNumberContact = {
  recordID: '177C371E-701D-42F8-A03B-C61CA31627F6',
  backTitle: '',
  jobTitle: 'Producer',
  emailAddresses: [],
  urlAddresses: [],
  phoneNumbers: [
    {label: 'mobile', number: '(555) 564-8583'},
    {label: 'main', number: '(415) 555-3695'},
  ],
  postalAddresses: [],
  thumbnailPath: 'https://static.thenounproject.com/png/252491-200.png',
  company: '',
  middleName: '',
  imAddresses: [],
  givenName: '',
  birthday: {day: 20, month: 1, year: 1978},
  hasThumbnail: true,
  familyName: '',
  isStarred: false,
  prefix: '',
  suffix: '',
  displayName: 'Kate Bell',
  note: '',
  department: '',
};

export const noDisplayNameContact = {
  recordID: '177C371E-701D-42F8-A03B-C61CA31627F6',
  backTitle: '',
  jobTitle: 'Producer',
  emailAddresses: [],
  urlAddresses: [],
  phoneNumbers: [
    {label: 'mobile', number: '(555) 564-8583'},
    {label: 'main', number: '(415) 555-3695'},
  ],
  postalAddresses: [],
  thumbnailPath: '',
  company: '',
  middleName: '',
  imAddresses: [],
  givenName: '',
  birthday: {day: 20, month: 1, year: 1978},
  hasThumbnail: false,
  familyName: '',
  isStarred: false,
  prefix: '',
  suffix: '',
  displayName: 'Kate Bell',
  note: '',
  department: '',
};

export const singleContact = {
  recordID: '177C371E-701D-42F8-A03B-C61CA31627F6',
  backTitle: '',
  jobTitle: 'Producer',
  emailAddresses: [],
  urlAddresses: [],
  phoneNumbers: [
    {label: 'mobile', number: '(555) 564-8583'},
    {label: 'main', number: '(415) 555-3695'},
  ],
  postalAddresses: [],
  thumbnailPath: '',
  company: '',
  middleName: '',
  imAddresses: [],
  givenName: 'Kate',
  birthday: {day: 20, month: 1, year: 1978},
  hasThumbnail: false,
  familyName: 'Bell',
  isStarred: false,
  prefix: '',
  suffix: '',
  displayName: 'Kate Bell',
  note: '',
  department: '',
};

export const tempContact = [
  {
    jobTitle: 'Producer',
    emailAddresses: [{label: 'work', email: 'kate-bell@mac.com'}],
    urlAddresses: [{label: 'homepage', url: 'www.icloud.com'}],
    phoneNumbers: [{label: 'mobile', number: '(555) 564-8583'}],
    recordID: '177C371E-701D-42F8-A03B-C61CA31627F6',
    postalAddresses: [
      {
        state: 'CA',
        label: 'work',
        region: 'CA',
        postCode: '94010',
        country: '',
        city: 'Hillsborough',
        street: '165 Davis Street',
      },
    ],
    thumbnailPath: '',
    company: 'Creative Consulting',
    middleName: '',
    imAddresses: [],
    givenName: 'Kate',
    birthday: {day: 20, month: 1, year: 1978},
    hasThumbnail: false,
    familyName: 'Bell',
  },
  {
    jobTitle: '',
    emailAddresses: [{label: 'home', email: 'd-higgins@mac.com'}],
    urlAddresses: [],
    phoneNumbers: [
      {label: 'home', number: '555-478-7672'},
      {label: 'mobile', number: '(408) 555-5270'},
      {label: 'home fax', number: '(408) 555-3514'},
    ],
    recordID: 'AB211C5F-9EC9-429F-9466-B9382FF61035',
    postalAddresses: [
      {
        state: 'CA',
        label: 'home',
        region: 'CA',
        postCode: '94925',
        country: 'USA',
        city: 'Corte Madera',
        street: '332 Laguna Street',
      },
    ],
    thumbnailPath: '',
    company: '',
    middleName: '',
    imAddresses: [],
    givenName: 'Daniel',
    hasThumbnail: false,
    familyName: 'Higgins',
  },
  {
    jobTitle: '',
    emailAddresses: [{label: 'work', email: 'John-Appleseed@mac.com'}],
    urlAddresses: [],
    phoneNumbers: [
      {label: 'mobile', number: '888-555-5512'},
      {label: 'home', number: '888-555-1212'},
    ],
    recordID: '410FE041-5C4E-48DA-B4DE-04C15EA3DBAC',
    postalAddresses: [
      {
        state: 'GA',
        label: 'work',
        region: 'GA',
        postCode: '30303',
        country: 'USA',
        city: 'Atlanta',
        street: '3494 Kuhl Avenue',
      },
      {
        state: 'GA',
        label: 'home',
        region: 'GA',
        postCode: '30303',
        country: 'USA',
        city: 'Atlanta',
        street: '1234 Laurel Street',
      },
    ],
    thumbnailPath: '',
    company: '',
    middleName: '',
    imAddresses: [],
    givenName: 'John',
    birthday: {day: 22, month: 6, year: 1980},
    hasThumbnail: false,
    familyName: 'Appleseed',
  },
  {
    jobTitle: '',
    emailAddresses: [{label: 'home', email: 'anna-haro@mac.com'}],
    urlAddresses: [],
    phoneNumbers: [{label: 'home', number: '555-522-8243'}],
    recordID: 'F57C8277-585D-4327-88A6-B5689FF69DFE',
    postalAddresses: [
      {
        state: 'CA',
        label: 'home',
        region: 'CA',
        postCode: '94965',
        country: 'USA',
        city: 'Sausalito',
        street: '1001  Leavenworth Street',
      },
    ],
    thumbnailPath: '',
    company: '',
    middleName: '',
    imAddresses: [],
    givenName: 'Anna',
    birthday: {day: 29, month: 8, year: 1985},
    hasThumbnail: false,
    familyName: 'Haro',
  },
  {
    jobTitle: 'Portfolio Manager',
    emailAddresses: [{label: 'work', email: 'hank-zakroff@mac.com'}],
    urlAddresses: [],
    phoneNumbers: [
      {label: 'work', number: '(555) 766-4823'},
      {label: 'other', number: '(707) 555-1854'},
    ],
    recordID: '2E73EE73-C03F-4D5F-B1E8-44E85A70F170',
    postalAddresses: [
      {
        state: 'CA',
        label: 'work',
        region: 'CA',
        postCode: '94901',
        country: '',
        city: 'San Rafael',
        street: '1741 Kearny Street',
      },
    ],
    thumbnailPath: '',
    company: 'Financial Services Inc.',
    middleName: 'M.',
    imAddresses: [],
    givenName: 'Hank',
    hasThumbnail: false,
    familyName: 'Zakroff',
  },
  {
    jobTitle: '',
    emailAddresses: [],
    urlAddresses: [],
    phoneNumbers: [{label: 'home', number: '555-610-6679'}],
    recordID: 'E94CD15C-7964-4A9B-8AC4-10D7CFB791FD',
    postalAddresses: [
      {
        state: 'CA',
        label: 'home',
        region: 'CA',
        postCode: '94920',
        country: 'USA',
        city: 'Tiburon',
        street: '1747 Steuart Street',
      },
    ],
    thumbnailPath: '',
    company: '',
    middleName: '',
    imAddresses: [],
    givenName: 'David',
    birthday: {day: 15, month: 6, year: 1998},
    hasThumbnail: false,
    familyName: 'Taylor',
  },
];
